# Generated by Django 5.0.3 on 2024-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('DeliveryMan', 'DeliveryMan')]),
        ),
    ]
