# Generated by Django 5.0.3 on 2024-03-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('DeliveryMan', 'DeliveryMan'), ('Admin', 'Admin')]),
        ),
    ]
