# Generated by Django 4.2.10 on 2024-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage_rename_image_product_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product/multiImages/"),
        ),
    ]
