# Generated by Django 4.2.10 on 2024-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images",),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.DeleteModel(name="ProductImage",),
        migrations.AddField(
            model_name="product", name="images", field=models.JSONField(default=list),
        ),
    ]
