# Generated by Django 4.2.10 on 2024-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productimage_product_thumbnail_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product/images/"),
        ),
    ]
