# Generated by Django 4.2.10 on 2024-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="static/images/notfound.png", upload_to="product/images/"
            ),
        ),
    ]
