# Generated by Django 5.0.2 on 2024-03-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
    ]
