# Generated by Django 5.0.2 on 2024-03-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_new_product_newprice_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_M',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_XL',
            field=models.IntegerField(default=0),
        ),
    ]
