# Generated by Django 5.0.2 on 2024-03-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
