# Generated by Django 4.2.10 on 2024-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_remove_product_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images",),
        migrations.RemoveField(model_name="product", name="thumbnail",),
        migrations.AddField(
            model_name="product",
            name="subImageFour",
            field=models.ImageField(blank=True, null=True, upload_to="product/images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="subImageOne",
            field=models.ImageField(blank=True, null=True, upload_to="product/images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="subImageThree",
            field=models.ImageField(blank=True, null=True, upload_to="product/images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="subImageTwo",
            field=models.ImageField(blank=True, null=True, upload_to="product/images/"),
        ),
        migrations.DeleteModel(name="ProductImage",),
    ]
