# Generated by Django 5.0.2 on 2024-03-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_sizeable_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizeable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
