# Generated by Django 5.0.2 on 2024-03-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subcategory'),
        ('product', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
        ),
    ]
