# Generated by Django 5.0.2 on 2024-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/notfound.png', upload_to='category/images'),
        ),
        migrations.AddField(
            model_name='category',
            name='itemCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
