# Generated by Django 5.0.2 on 2024-03-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
