# Generated by Django 5.0.2 on 2024-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/images/'),
        ),
    ]
