# Generated by Django 5.0.2 on 2024-03-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_rate_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
