# Generated by Django 5.0.3 on 2024-03-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
