# Generated by Django 5.0.3 on 2024-03-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_paymenthistory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
