# Generated by Django 5.0.2 on 2024-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/images/notfound.png', upload_to='banners/images')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
