# Generated by Django 5.0.2 on 2024-03-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_total_price_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
    ]
