# Generated by Django 5.0.2 on 2024-03-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtmp',
            name='size',
            field=models.CharField(blank=True, choices=[('one_size', 'one_size'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, null=True),
        ),
    ]
