# Generated by Django 5.0.2 on 2024-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderitemtmp_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('S', 'shipped'), ('D', 'delivered'), ('C', 'Canceled')], default='P', max_length=50),
        ),
    ]
