# Generated by Django 5.0.3 on 2024-03-26 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_category_itemcount'),
        ('order', '0015_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
