# Generated by Django 5.0.2 on 2024-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
